version: 0.2
env:
  secrets-manager:
    DOCKERHUB_TOKEN: sam-dockerhub:token
    DOCKERHUB_USER: sam-dockerhub:user
phases:
  pre_build:
    commands:
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin
  build:
    commands:
      - docker build -t tic-tac-toe-game:latest .
  post_build:
    commands:
      - docker tag tic-tac-toe-game:latest ${DOCKERHUB_USER}/tic-tac-toe-game:latest
      - docker push ${DOCKERHUB_USER}/tic-tac-toe-game:latest