version: 0.2
env:
  variables:
    ECR_REPO_NAME: tic-tac-toe-game
  parameter-store:
    DOCKERHUB_TOKEN: /dockerhub/token 
    DOCKERHUB_USER: /dockerhub/user  
phases:
  pre_build:
    commands:
      # Docker Hub login
      - echo "Login to DockerHub..."
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin
      # ECR Login
      - echo "Login to ECR..."
      - ECR_MAIN_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_MAIN_URI}
      # - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 767397705569.dkr.ecr.ap-northeast-2.amazonaws.com
      - ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPO_NAME}:latest"
      - echo "ECR Image URI: ${ECR_IMAGE_URI}"
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t tic-tac-toe-game:latest .
  post_build:
    commands:
      - echo "Pushing the Docker image to DockerHub..."
      - docker tag tic-tac-toe-game:latest ${ECR_IMAGE_URI}
      - docker push ${ECR_IMAGE_URI}